=== pgrafe/php-code-generator/xsd/enum.xsd
<?xml version="1.0"?>
<!-- https://www.w3schools.com/xml/schema_intro.asp -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.w3schools.com"
           xmlns="http://www.w3schools.com"
           elementFormDefault="qualified">

    <xs:element name="enum">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="definition">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="comment" maxOccurs="10"/>
                            <xs:element name="const" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="name" use="required">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:pattern value="([A-Z_])+"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                    <xs:attribute name="value" use="required">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:pattern value="([a-zA-Z0-9_\-])+"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                    <xs:attribute name="comment" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="fqcn" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:pattern value="([a-zA-Z\\])+"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="type" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="int"/>
                                    <xs:enumeration value="string"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== pgrafe/php-code-generator/config/enum/php-type.pgcg.xml
<?xml version="1.0"?>

<enum xmlns="http://www.w3schools.com"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.w3schools.com ../../xsd/enum.xsd">
    <definition fqcn="PGrafe\PhpCodeGenerator\Enum\PhpType" type="string">
        <comment>php types</comment>
        <comment>These will be mapped to Doctrine Types</comment>
        <const comment="php array" name="ARRAY" value="array"/>
        <const comment="php int value" name="INT" value="int"/>
        <const comment="php float value" name="FLOAT" value="float"/>
        <const comment="php DateTime object" name="DATETIME" value="DateTime"/>
        <const comment="php bool value" name="BOOL" value="bool"/>
        <const comment="php string value" name="STRING" value="string"/>
    </definition>
</enum>
